---
- hosts: webapp
  
  tasks:
  - name: connection check
    maven_artifact:
      group_id=arcode
      artifact_id=arcode
      extension=war
      repository_url=http://localhost:8081/repository/mvnnexusrepo/arcode/arcode/1.0-SNAPSHOT
      username=admin
      password=admin123
      dest=/usr/share/tomcat/webapps/prd.war
