---
- hosts: webapp
  become: true  
  tasks:
  - name: Deploy to tomcat 
    maven_artifact:
      group_id: arcode
      artifact_id: arcode
      extension: war
      repository_url: http://192.168.122.1:8081/repository/mvnnexusrepo/
      dest: /usr/share/tomcat/webapps/prd.war
      version: 1.0-SNAPSHOT
